
version: '3'

services:
  cfgsvr1:
    container_name: cfgsvr1
    image: mongo:4.0.6
    command: mongod --configsvr --replSet cfgrs --port 27017 --dbpath /data/db
    ports:
      - 40001:27017
    volumes:
      - cfgsvr1a:/data/db
    environment:
      - MONGODB_REPLICA_SET_MODE=primary

  cfgsvr2:
    container_name: cfgsvr2
    image: mongo:4.0.6
    command: mongod --configsvr --replSet cfgrs --port 27017 --dbpath /data/db
    ports:
      - 40002:27017
    volumes:
      - cfgsvr2a:/data/db
    environment:
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_PRIMARY_HOST=cfgsvr1

  cfgsvr3:
    container_name: cfgsvr3
    image: mongo:4.0.6
    command: mongod --configsvr --replSet cfgrs --port 27017 --dbpath /data/db
    ports:
      - 40003:27017
    volumes:
      - cfgsvr3a:/data/db
    environment:
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_PRIMARY_HOST=cfgsvr1

  mongos:
    container_name: mongos
    image: mongo:4.0.6
    command: mongos --configdb cfgrs/localhost:40001,localhost:40002,localhost:40003 --bind_ip 0.0.0.0  --port 27017
    ports:
      - 60000:27017
      
volumes:
  cfgsvr1a: {}
  cfgsvr2a: {}
  cfgsvr3a: {}
  shard1svr1: {}
  shard1svr2: {}
  shard1svr3: {}
  shard2svr1: {}
  shard2svr2: {}
  shard2svr3: {}

