
version: '3'

services:
  cfgsvr1:
    container_name: cfgsvr1
    image: mongo:4.0.6
    command: mongod --configsvr --replSet cfgrs --port 27017 --dbpath /data/db
    ports:
      - 40001:27017
    volumes:
      - cfgsvr1a:/data/db

  cfgsvr2:
    container_name: cfgsvr2
    image: mongo:4.0.6
    command: mongod --configsvr --replSet cfgrs --port 27017 --dbpath /data/db
    ports:
      - 40002:27017
    volumes:
      - cfgsvr2a:/data/db

  cfgsvr3:
    container_name: cfgsvr3
    image: mongo:4.0.6
    command: mongod --configsvr --replSet cfgrs --port 27017 --dbpath /data/db
    ports:
      - 40003:27017
    volumes:
      - cfgsvr3a:/data/db

volumes:
  cfgsvr1a: {}
  cfgsvr2a: {}
  cfgsvr3a: {}
